platform :ios, '15.1'

use_frameworks! :linkage => :static  # ✅ 무조건 적용 (조건부 ❌)
use_modular_headers!

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-permissions/scripts/setup'

prepare_react_native_project!

setup_permissions([
  'Camera',
  'LocationAccuracy',
  'LocationAlways',
  'LocationWhenInUse',
  'Microphone',
])

target 'EscapeSMU' do
  config = use_native_modules!

  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseAuth', :modular_headers => true
  $RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # ✅ 필수: Swift 모듈 + 헤더 빌드 대응
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['DEFINES_MODULE'] = 'YES'
        # config.build_settings['SWIFT_OBJC_BRIDGING_HEADER'] = 'EscapeSMU-Bridging-Header.h'
        # config.build_settings['SWIFT_OBJC_INTERFACE_HEADER_NAME'] = 'EscapeSMU-Swift.h'
      end
    end
  end
end