# # Resolve react_native_pods.rb with node to allow for hoisting
# # require Pod::Executable.execute_command('node', ['-p',
# #   'require.resolve(
# #     "react-native/scripts/react_native_pods.rb",
# #     {paths: [process.argv[1]]},
# #   )', __dir__]).strip



# def node_require(script)
#     # Resolve script with node to allow for hoisting
#     require Pod::Executable.execute_command('node', ['-p',
#       "require.resolve(
#         '#{script}',
#         {paths: [process.argv[1]]},
#       )", __dir__]).strip
# end

# # Use it to require both react-native's and this package's scripts:
# node_require('react-native/scripts/react_native_pods.rb')
# node_require('react-native-permissions/scripts/setup.rb')

# platform :ios, '15.1'
# prepare_react_native_project!

# # ⬇️ uncomment the permissions you need
# setup_permissions([
#   # 'AppTrackingTransparency',
#   # 'Bluetooth',
#   # 'Calendars',
#   # 'CalendarsWriteOnly',
#   'Camera',
#   # 'Contacts',
#   # 'FaceID',
#   'LocationAccuracy',
#   'LocationAlways',
#   'LocationWhenInUse',
#   # 'MediaLibrary',
#   # 'Microphone',
#   # 'Motion',
#   # 'Notifications',
#   # 'PhotoLibrary',
#   # 'PhotoLibraryAddOnly',
#   # 'Reminders',
#   # 'Siri',
#   # 'SpeechRecognition',
#   # 'StoreKit',
# ])



# use_modular_headers! # ✅ 전역 적용 (문제 없으면 이게 제일 간단)


# linkage = ENV['USE_FRAMEWORKS']
# if linkage != nil
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => :static
# end

# $RNFirebaseAsStaticFramework = true

# target 'EscapeSMU' do
#   config = use_native_modules!

#   # ✅ Firebase 인증만 설치
#   pod 'FirebaseAuth', :modular_headers => true

#   use_react_native!(
#     :path => config[:reactNativePath],
#     # An absolute path to your application root.
#     :app_path => "#{Pod::Config.instance.installation_root}/.."
#   )

#   post_install do |installer|
#     # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
#     react_native_post_install(
#       installer,
#       config[:reactNativePath],
#       :mac_catalyst_enabled => false,
#       # :ccache_enabled => true
#     )
#   end
# end













platform :ios, '15.1'

use_frameworks! :linkage => :static  # ✅ 무조건 적용 (조건부 ❌)
use_modular_headers!

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-permissions/scripts/setup'

prepare_react_native_project!

setup_permissions([
  'Camera',
  'LocationAccuracy',
  'LocationAlways',
  'LocationWhenInUse',
])

target 'EscapeSMU' do
  config = use_native_modules!

  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseAuth', :modular_headers => true
  $RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # ✅ 필수: Swift 모듈 + 헤더 빌드 대응
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['DEFINES_MODULE'] = 'YES'
        # config.build_settings['SWIFT_OBJC_BRIDGING_HEADER'] = 'EscapeSMU-Bridging-Header.h'
        # config.build_settings['SWIFT_OBJC_INTERFACE_HEADER_NAME'] = 'EscapeSMU-Swift.h'
      end
    end
  end
end